---
include:
  # https://github.com/mctechnology17/zmk-nice-oled
  - board: eyelash_corne_left
    shield: corne_left nice_view_adapter nice_epaper
  - board: eyelash_corne_right
    shield: corne_right nice_view_adapter nice_epaper

  # Bongo Cat: https://github.com/dsifry/nice-view-mod
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_view_custom
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_view_custom

  # Default
  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
