---
include:
  # Bongo Cat: https://github.com/dsifry/nice-view-mod
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_view_custom
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  # - board: eyelash_corne_right
  #   shield: nice_view_adapter nice_view_custom

  # https://github.com/mctechnology17/zmk-nice-oled
  # - board: eyelash_corne_left
  #   shield: nice_view_adapter nice_epaper
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  # - board: eyelash_corne_right
  #   shield: nice_view_adapter nice_epaper

  # https://github.com/whoop-t/nice-one-punch-ok
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_one_punch_ok
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  # https://github.com/qwerty22121998/nice-view-anim
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_view_anim
    cmake-args: -DCONFIG_ZMK_NICE_VIEW_ANIM_VARIANT=1

  # Default
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging

  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
