---
include:
  # Bongo Cat: https://github.com/dsifry/nice-view-mod
  # - board: eyelash_corne_left
  #   shield: nice_view_adapter nice_view_custom
  # - board: eyelash_corne_right
  #   shield: nice_view_adapter nice_view_custom

  # https://github.com/mctechnology17/zmk-nice-oled
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_epaper
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_epaper

  # https://github.com/GPeye/hammerbeam-slideshow
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_epaper
    artifact-name: corne_hammerbeam_left
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_view_custom
    artifact-name: corne_hammerbeam_right

  # Default
  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
