manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: MrBanh
      url-base: https://github.com/MrBanh
  projects:
    - name: eyelash_corne
      url: https://github.com/MrBanh/zmk-new_corne
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-bongo-cat
      remote: MrBanh
      revision: main
  self:
    path: config
