manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: dsifry
      url-base: https://github.com/dsifry

    - name: mctechnology17
      url-base: https://github.com/mctechnology17

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: eyelash_corne
      url: https://github.com/MrBanh/zmk-new_corne
      revision: main

    - name: nice-view-mod
      remote: dsifry
      revision: main

    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main

  self:
    path: config
